### PR TITLE
debugged the JavaScript file

### PR DESCRIPTION
**Pull request by JafariM**

### CODE REVIEW

**Review by tamimkh — APPROVED** [review]
Looks good! Everything in the app seems to be working. 

One thing I noticed though is that it seems like you forgot to specify the correct [base repository](https://github.com/Code-the-Dream-School/intro-to-programming/blob/main/instructions/common/how-to-pull-request.md#step-4-select-the-base-repository-dropdown-and-choose-your-forked-repository). You probably want to do this before merging your PR

**Comment by JafariM** [comment]
Thank you for your review. Can I change the base repository now or I should make a new pull request?

**Comment by tamimkh** [comment]
If you are able to change the base repository then you should change it and then merge. Otherwise you will need to make a new PR and then merge it

**Comment by JafariM** [comment]
I could not change the repository, so I made a new PR and merged.

**Comment by mamooredesigns** [comment]
Students should pull request to their own forked copy of the repository instead of the code the dream school repository

**Pull request closed without merging**
